name: Deploy Server
on:
  push:
    paths:
      - 'server/**/*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Trigger deployment
            env:
              deploy_hook: ${{ secrets.SERVER_DEPLOY_HOOK }}
            run: |
              curl -X POST "$deploy_hook"